import { STUDENT_SOLICITATIONS_FILTER_MAP, STUDENT_SOLICITATIONS_FROM_PROFESSOR_VIEW_FILTER_MAP } from "./filters/studentSolicitations.map.filter";
import { TO_SCHEDULE_PROFESSORS_FILTER_MAP } from "./filters/toScheduleProfessors.map.filter";
import { PROFESSOR_APPOINTMENTS_FILTER_MAP, STUDENT_APPOINTMENTS_FILTER_MAP } from "./filters/userAppointments.map.filter";
import { PROFESSOR_APPOINTMENTS_HISTORY_FILTER_MAP, STUDENT_APPOINTMENTS_HISTORY_FILTER_MAP,  } from "./filters/userAppointmentHistory.map.filter";
import { USERS_LIST_BY_ROLE_FILTER_MAP } from "./filters/usersListByRole.map.filter";
import { REGISTERED_MANAGERS_FILTER_MAP, REGISTERED_PROFESSORS_FILTER_MAP, REGISTERED_STUDENTS_FILTER_MAP } from "./filters/registeredUsers.map.filter";

export const SELECT_OPTIONS_SCHEMA_MAP = {
  REGISTERED_STUDENTS_FILTER                       : REGISTERED_STUDENTS_FILTER_MAP,
  REGISTERED_PROFESSORS_FILTER                     : REGISTERED_PROFESSORS_FILTER_MAP,
  REGISTERED_MANAGERS_FILTER                       : REGISTERED_MANAGERS_FILTER_MAP,

  USERS_LIST_BY_ROLE_FILTER                        : USERS_LIST_BY_ROLE_FILTER_MAP,
  
  STUDENT_APPOINTMENTS_FILTER                      : STUDENT_APPOINTMENTS_FILTER_MAP,
  PROFESSOR_APPOINTMENTS_FILTER                    : PROFESSOR_APPOINTMENTS_FILTER_MAP,
  
  TO_SCHEDULE_PROFESSORS_FILTER                    : TO_SCHEDULE_PROFESSORS_FILTER_MAP,

  STUDENT_SOLICITATIONS_FILTER                     : STUDENT_SOLICITATIONS_FILTER_MAP,
  STUDENT_SOLICITATIONS_FROM_PROFESSOR_VIEW_FILTER : STUDENT_SOLICITATIONS_FROM_PROFESSOR_VIEW_FILTER_MAP,

  STUDENT_APPOINTMENTS_HISTORY_FILTER              : STUDENT_APPOINTMENTS_HISTORY_FILTER_MAP,
  PROFESSOR_APPOINTMENTS_HISTORY_FILTER            : PROFESSOR_APPOINTMENTS_HISTORY_FILTER_MAP
} as const;