import { STUDENT_APPOINTMENT_FILTER_MAP } from "./filters/studentAppoitment.map.filter";
import { STUDENT_APPOINTMENTS_HISTORY_FILTER_MAP } from "./filters/studentAppointmentsHistory.map.filter";
import { STUDENT_SOLICITATIONS_FILTER_MAP, STUDENT_SOLICITATIONS_FROM_PROFESSOR_VIEW_FILTER_MAP } from "./filters/studentSolicitations.map.filter";
import { TO_SCHEDULE_PROFESSORS_FILTER_MAP } from "./filters/toScheduleProfessors.map.filter";
import { PROFESSOR_APPOINTMENT_FILTER_MAP } from "./filters/professorAppointments.map.filter";
import { PROFESSOR_APPOINTMENTS_HISTORY_FILTER_MAP } from "./filters/professorAppointmentsHistory.map.filter";

export const SELECT_OPTIONS_SCHEMA_MAP = {
  STUDENT_APPOINTMENT_FILTER                       : STUDENT_APPOINTMENT_FILTER_MAP,
  PROFESSOR_APPOINTMENT_FILTER                     : PROFESSOR_APPOINTMENT_FILTER_MAP,
  TO_SCHEDULE_PROFESSORS_FILTER                    : TO_SCHEDULE_PROFESSORS_FILTER_MAP,
  STUDENT_SOLICITATIONS_FILTER                     : STUDENT_SOLICITATIONS_FILTER_MAP,
  STUDENT_SOLICITATIONS_FROM_PROFESSOR_VIEW_FILTER : STUDENT_SOLICITATIONS_FROM_PROFESSOR_VIEW_FILTER_MAP,
  STUDENT_APPOINTMENTS_HISTORY_FILTER              : STUDENT_APPOINTMENTS_HISTORY_FILTER_MAP,
  PROFESSOR_APPOINTMENTS_HISTORY_FILTER            : PROFESSOR_APPOINTMENTS_HISTORY_FILTER_MAP
} as const;